[project]
name = "oyapri"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
  "fastapi==0.115.0",
  "uvicorn==0.30.6",
  "boto3==1.34.162",
  "python-multipart==0.0.9",
  "pymysql==1.1.1",
  "pillow==10.4.0",
  "pytesseract==0.3.10",
]

[dependency-groups]
dev = []
